apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"nano","example-webhook-enabled":"true"},"name":"service-nano","namespace":"default"},"spec":{"ports":[{"name":"http","port":70,"protocol":"TCP","targetPort":50}],"selector":{"app":"nano"}}}
  creationTimestamp: "2024-01-30T10:35:01Z"
  labels:
    app: nano
    author: gopesh
    example-webhook-enabled: "true"
    operation: UPDATE
  name: service-nano
  namespace: default
spec:
  clusterIP: 10.104.9.23
  clusterIPs:
  - 10.104.9.23
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 70
    protocol: TCP
    targetPort: 50
  selector:
    app: nano
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
