apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"nginx","example-webhook-enabled":"true"},"name":"nginx-service","namespace":"default"},"spec":{"ports":[{"name":"http","port":600,"protocol":"TCP","targetPort":30}],"selector":{"app":"nginx"}}}
  creationTimestamp: "2024-01-30T10:55:22Z"
  labels:
    app: nginx
    author: minikube-user
    example-webhook-enabled: "true"
    operation: UPDATE
  name: nginx-service
  namespace: default
spec:
  clusterIP: 10.99.229.250
  clusterIPs:
  - 10.99.229.250
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 600
    protocol: TCP
    targetPort: 30
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
