apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"nginx","example-webhook-enabled":"true"},"name":"nginx-service-test","namespace":"default"},"spec":{"ports":[{"name":"http","port":900,"protocol":"TCP","targetPort":30}],"selector":{"app":"nginx"}}}
  creationTimestamp: "2024-01-31T08:25:14Z"
  labels:
    app: nginx
    author: minikube-user
    example-webhook-enabled: "true"
    operation: CREATE
  name: nginx-service-test
  namespace: default
spec:
  clusterIP: 10.109.20.98
  clusterIPs:
  - 10.109.20.98
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 900
    protocol: TCP
    targetPort: 30
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
