apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"webhook-service","namespace":"metallb-system"},"spec":{"ports":[{"port":443,"targetPort":9443}],"selector":{"component":"controller"}}}
  creationTimestamp: "2024-01-02T05:31:56Z"
  name: webhook-service
  namespace: metallb-system
spec:
  clusterIP: 10.110.236.238
  clusterIPs:
  - 10.110.236.238
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    component: controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
